language: java
sudo: false

jdk:
  - oraclejdk8

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

addons:
  sonarcloud:
    organization: "kikalasobhe-github"
    token:
      secure: "$SONAR_TOKEN"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
before_install:
  - chmod +x gradlew
after_success:
  - ./gradlew sonarqube
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  api_key:
      secure: "$HEROKU_TOKEN"
  app: gollesobhe