language: java
sudo: false

jdk:
  - oraclejdk8

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
before_install:
  - chmod +x gradlew